<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\ERechnung.Core\ERechnung.Core.csproj" />
    <ProjectReference Include="..\ERechnung.Data\ERechnung.Data.csproj" />
    <ProjectReference Include="..\ERechnung.XML\ERechnung.XML.csproj" />
    <ProjectReference Include="..\ERechnung.PDF\ERechnung.PDF.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="SQLitePCLRaw.bundle_e_sqlite3" Version="2.1.12" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

</Project>
